#pragma once
/* NINJA Basic model
*
* Generated by SAMDL
*
*/

#include "SADXModLoader.h"
#include "ninja.h"

/* NINJA Basic (with Sonic Adventure DX additions) model
*
* Generated by SAMDL
*
*/

enum CHAO_OBJECTTexName
{
	CHAO_OBJECTTexName_monita01,
	CHAO_OBJECTTexName_monita02,
	CHAO_OBJECTTexName_monita03,
	CHAO_OBJECTTexName_monita05,
	CHAO_OBJECTTexName_monita04,
	CHAO_OBJECTTexName_plant_02,
	CHAO_OBJECTTexName_mi_02,
	CHAO_OBJECTTexName_plant06,
	CHAO_OBJECTTexName_vms_e,
	CHAO_OBJECTTexName_vms06,
	CHAO_OBJECTTexName_r_sonic2,
	CHAO_OBJECTTexName_r_tailes2,
	CHAO_OBJECTTexName_r_nuckles2,
	CHAO_OBJECTTexName_r_amy,
	CHAO_OBJECTTexName_r_e102,
	CHAO_OBJECTTexName_r_big3,
	CHAO_OBJECTTexName_r_chao,
	CHAO_OBJECTTexName_vms_kai,
	CHAO_OBJECTTexName_vms_red,
	CHAO_OBJECTTexName_plant05,
	CHAO_OBJECTTexName_kiratsubu01,
	CHAO_OBJECTTexName_kiratsubu02,
	CHAO_OBJECTTexName_kiratsubu03,
	CHAO_OBJECTTexName_kiratsubu05,
	CHAO_OBJECTTexName_kiratsubu04,
	CHAO_OBJECTTexName_kiratsubu06,
	CHAO_OBJECTTexName_kiratsubu07,
	CHAO_OBJECTTexName_kiratsubu08,
	CHAO_OBJECTTexName_mi_03,
	CHAO_OBJECTTexName_mi_01,
	CHAO_OBJECTTexName_mi_orenge,
	CHAO_OBJECTTexName_al_hafl01,
	CHAO_OBJECTTexName_al_hafl02,
	CHAO_OBJECTTexName_al_hafl03,
	CHAO_OBJECTTexName_alm_blue,
	CHAO_OBJECTTexName_alm_kuki,
	CHAO_OBJECTTexName_alm_purple,
	CHAO_OBJECTTexName_alm_red,
	CHAO_OBJECTTexName_alm_yellow,
	CHAO_OBJECTTexName_alm_sgo01,
	CHAO_OBJECTTexName_alm_sgo02,
	CHAO_OBJECTTexName_alm_sgo03,
	CHAO_OBJECTTexName_alm_sgo04,
	CHAO_OBJECTTexName_alm_sek01,
	CHAO_OBJECTTexName_alm_sek02,
	CHAO_OBJECTTexName_alm_sek03,
	CHAO_OBJECTTexName_alm_kgk01,
	CHAO_OBJECTTexName_alm_kgk02,
	CHAO_OBJECTTexName_alm_kgk03,
	CHAO_OBJECTTexName_hana2_hanap,
	CHAO_OBJECTTexName_hana2_hanaw,
	CHAO_OBJECTTexName_hana2_happa,
	CHAO_OBJECTTexName_vms_03,
	CHAO_OBJECTTexName_vms_bl,
	CHAO_OBJECTTexName_cr_ha,
	CHAO_OBJECTTexName_vms_b02,
	CHAO_OBJECTTexName_vms_01,
	CHAO_OBJECTTexName_vms1,
	CHAO_OBJECTTexName_vms2,
	CHAO_OBJECTTexName_al_ws01,
	CHAO_OBJECTTexName_al_ws02,
	CHAO_OBJECTTexName_al_ws03,
	CHAO_OBJECTTexName_al_ws10,
	CHAO_OBJECTTexName_al_ws13,
	CHAO_OBJECTTexName_al_ws11,
	CHAO_OBJECTTexName_al_ws14,
	CHAO_OBJECTTexName_al_ws12,
	CHAO_OBJECTTexName_al_ws15,
	CHAO_OBJECTTexName_al_wseff,
	CHAO_OBJECTTexName_mi_gen02,
	CHAO_OBJECTTexName_al_ws04,
	CHAO_OBJECTTexName_al_ws05,
	CHAO_OBJECTTexName_al_ws06,
	CHAO_OBJECTTexName_al_ws07,
	CHAO_OBJECTTexName_al_ws08,
	CHAO_OBJECTTexName_al_ws09,
	CHAO_OBJECTTexName_al_wsm01,
	CHAO_OBJECTTexName_al_wsm02
};

NJS_MATERIAL matlist_0017D0BC[] = {
	{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, CHAO_OBJECTTexName_alm_kgk01, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_CLAMP_V | NJD_FLAG_CLAMP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_ALPHA | NJD_FLAG_USE_TEXTURE | NJD_FLAG_DOUBLE_SIDE | NJD_DA_INV_SRC | NJD_SA_SRC },
{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, CHAO_OBJECTTexName_alm_kgk02, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_V | NJD_FLAG_FLIP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC },
{ { 0xFFB2B2B2 },{ 0xFFFFFFFF }, 11, CHAO_OBJECTTexName_alm_kgk03, NJD_D_100 | NJD_FILTER_BILINEAR | NJD_FLAG_FLIP_V | NJD_FLAG_FLIP_U | NJD_FLAG_IGNORE_SPECULAR | NJD_FLAG_USE_TEXTURE | NJD_DA_INV_SRC | NJD_SA_SRC }
};

Sint16 poly_0017D0F8[] = {
	3, 0, 4, 2,
	10, 7, 2, 1, 4, 3, 6, 5, 8, 7, 2,
	0x8000u | 5, 4, 6, 0, 8, 2
};

Sint16 poly_0017D122[] = {
	7, 18, 15, 21, 19, 25, 13, 20,
	4, 23, 9, 25, 21,
	4, 25, 20, 23, 12,
	0x8000u | 7, 18, 14, 22, 17, 24, 11, 16,
	8, 18, 21, 22, 9, 24, 23, 16, 12
};

Sint16 poly_0017D168[] = {
	3, 16, 12, 10,
	0x8000u | 5, 14, 18, 10, 15, 19,
	5, 14, 17, 10, 11, 16,
	5, 12, 20, 10, 13, 19
};

NJS_TEX uv_0017D194[] = {
	{ 128, 128 },
{ 174, 80 },
{ 174, 174 },
{ 0, 254 },
{ 174, 174 },
{ 254, 254 },
{ 174, 80 },
{ 254, 0 },
{ 80, 80 },
{ 0 },
{ 80, 174 },
{ 0, 254 },
{ 174, 174 },
{ 174, 80 },
{ 80, 80 },
{ 128, 128 },
{ 80, 174 },
{ 174, 174 }
};

NJS_TEX uv_0017D1DC[] = {
	{ -210, 656 },
{ -263, 765 },
{ -260, 281 },
{ -315, 656 },
{ -373, 281 },
{ -373, 765 },
{ -431, 656 },
{ 22, 281 },
{ -117, 0 },
{ 136, 281 },
{ -260, 281 },
{ -373, 281 },
{ -431, 656 },
{ -487, 281 },
{ -483, 765 },
{ -210, 656 },
{ -164, 765 },
{ -162, 281 },
{ -117, 656 },
{ -72, 281 },
{ -70, 765 },
{ -24, 656 },
{ -210, 656 },
{ -260, 281 },
{ -162, 281 },
{ -117, 0 },
{ -72, 281 },
{ 22, 281 },
{ -24, 656 },
{ 26, 765 }
};

NJS_TEX uv_0017D254[] = {
	{ 438, -89 },
{ 510, 60 },
{ 255, -26 },
{ 97, -255 },
{ 71, -89 },
{ 255, -26 },
{ 0, 60 },
{ 141, 137 },
{ 97, -255 },
{ 255, -230 },
{ 255, -26 },
{ 412, -254 },
{ 438, -89 },
{ 510, 60 },
{ 368, 137 },
{ 255, -26 },
{ 254, 255 },
{ 141, 137 }
};

NJS_MESHSET_SADX meshlist_0017D29C[] = {
	{ NJD_MESHSET_TRIMESH | 0, 3, poly_0017D0F8, NULL, NULL, NULL, uv_0017D194, NULL },
{ NJD_MESHSET_TRIMESH | 1, 5, poly_0017D122, NULL, NULL, NULL, uv_0017D1DC, NULL },
{ NJD_MESHSET_TRIMESH | 2, 4, poly_0017D168, NULL, NULL, NULL, uv_0017D254, NULL }
};

NJS_VECTOR vertex_0017D2E4[] = {
	{ 0.006916f, 0.813148f, 0 },
{ 0.615627f, 1.369131f, 0 },
{ 0.22653f, 1.1736f, 0 },
{ 0, 1.369131f, 0.615627f },
{ 0, 1.1736f, 0.22653f },
{ -0.615627f, 1.369131f, 0 },
{ -0.22653f, 1.1736f, 0 },
{ 0, 1.369131f, -0.615627f },
{ 0, 1.1736f, -0.22653f },
{ 0, -3.008808f, 0 },
{ 0, 1.005f, 0 },
{ 1.469464f, 0.397163f, 2.022542f },
{ 2.377641f, 0.397163f, -0.772543f },
{ 0, 0.397163f, -2.5f },
{ -1.469463f, 0.397163f, 2.022542f },
{ -2.377641f, 0.397163f, -0.772542f },
{ 1.714693f, -0.08510599f, 0.557137f },
{ 0, -0.08510599f, 1.802935f },
{ -1.714693f, -0.08510599f, 0.557138f },
{ -1.059739f, -0.08510599f, -1.458605f },
{ 1.059739f, -0.08510599f, -1.458605f },
{ -1.652935f, -1.755888f, -0.537071f },
{ -1.021571f, -1.755887f, 1.406072f },
{ 1.652936f, -1.755888f, -0.537071f },
{ 1.021572f, -1.755887f, 1.406072f },
{ 0, -1.755888f, -1.738f }
};

NJS_VECTOR normal_0017D41C[] = {
{ -0.015249f, 0.9998839f, 0 },
{ -0.449018f, 0.893523f, 0 },
{ -0.592443f, 0.805612f, 0 },
{ 0, 0.893523f, -0.449018f },
{ 0.001448f, 0.808302f, -0.588767f },
{ 0.449018f, 0.893523f, 0 },
{ 0.5852f, 0.8108889f, 0 },
{ 0, 0.893523f, 0.449018f },
{ 0.001448f, 0.808302f, 0.588767f },
{ 0, -1, 0 },
{ 0, 1, 0 },
{ 0.520916f, 0.463237f, 0.716979f },
{ 0.842859f, 0.463237f, -0.273861f },
{ 0, 0.463237f, -0.886235f },
{ -0.520916f, 0.463237f, 0.716979f },
{ -0.842859f, 0.463237f, -0.273861f },
{ 0.913847f, 0.27698f, 0.296927f },
{ 0, 0.27698f, 0.960876f },
{ -0.913847f, 0.27698f, 0.296927f },
{ -0.564789f, 0.27698f, -0.777365f },
{ 0.564789f, 0.27698f, -0.777365f },
{ -0.802349f, -0.53691f, -0.260699f },
{ -0.495879f, -0.53691f, 0.682519f },
{ 0.802349f, -0.53691f, -0.260699f },
{ 0.495879f, -0.53691f, 0.682519f },
{ 0, -0.53691f, -0.84364f }
};

NJS_MODEL_SADX attach_0017D554 = { vertex_0017D2E4, normal_0017D41C, LengthOfArray<Sint32>(vertex_0017D2E4), meshlist_0017D29C, matlist_0017D0BC, LengthOfArray<Uint16>(meshlist_0017D29C), LengthOfArray<Uint16>(matlist_0017D0BC),{ 0, -0.819838f, -0.238729f }, 3.281239f, NULL };

NJS_OBJECT object_0017D57C = { NJD_EVAL_UNIT_POS | NJD_EVAL_UNIT_ANG | NJD_EVAL_UNIT_SCL | NJD_EVAL_BREAK, &attach_0017D554, 0, 0, 0, 0, 0, 0, 1, 1, 1, NULL, NULL };
